root = "."
testdata_dir = "testdata"
tmp_dir = ".gen/tmp"

[build]
args_bin = []
bin = ".gen/bin/serve.exe"
cmd = "go build -tags=use_disk,trace -o .gen/bin/serve.exe ."
delay = 50
exclude_dir = ["app", ".gen", ".git", ".github", "lib/core/ssr/app"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
pre_cmd = ["frizzante prebuild"]
post_cmd = ["frizzante postbuild"]
rerun = false
rerun_delay = 50
send_interrupt = true
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = false

[misc]
clean_on_exit = false

[proxy]
app_port = 0
enabled = false
proxy_port = 0

[screen]
clear_on_rebuild = false
keep_scroll = true
