// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package schema

type Result struct {
	ID          string `json:"id"`
	Address     string `json:"address"`
	Description string `json:"description"`
}
