// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package schema

import (
	"context"
)

const addResult = `-- name: AddResult :exec
insert into results(id,address,description) values(?1,?2,?3)
`

type AddResultParams struct {
	ID          string `json:"id"`
	Address     string `json:"address"`
	Description string `json:"description"`
}

func (q *Queries) AddResult(ctx context.Context, arg AddResultParams) error {
	_, err := q.db.ExecContext(ctx, addResult, arg.ID, arg.Address, arg.Description)
	return err
}

const findResultsByDescription = `-- name: FindResultsByDescription :many
select id, address, description from results where description like ?1
`

func (q *Queries) FindResultsByDescription(ctx context.Context, description string) ([]Result, error) {
	rows, err := q.db.QueryContext(ctx, findResultsByDescription, description)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Result
	for rows.Next() {
		var i Result
		if err := rows.Scan(&i.ID, &i.Address, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
